#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : brasero
Version  : 3.12.2
Release  : 3
URL      : https://download.gnome.org/sources/brasero/3.12/brasero-3.12.2.tar.xz
Source0  : https://download.gnome.org/sources/brasero/3.12/brasero-3.12.2.tar.xz
Summary  : Brasero Optical Media Burning library
Group    : Development/Tools
License  : GPL-2.0
Requires: brasero-bin = %{version}-%{release}
Requires: brasero-data = %{version}-%{release}
Requires: brasero-lib = %{version}-%{release}
Requires: brasero-license = %{version}-%{release}
Requires: brasero-locales = %{version}-%{release}
Requires: brasero-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-x11-3.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-base-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : pkgconfig(gstreamer-tag-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libburn-1)
BuildRequires : pkgconfig(libcanberra)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libisofs-1)
BuildRequires : pkgconfig(libnautilus-extension)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(totem-plparser)

%description
Brasero is a CD/DVD mastering tool for the GNOME Desktop. It is designed to be simple and easy to use.

%package bin
Summary: bin components for the brasero package.
Group: Binaries
Requires: brasero-data = %{version}-%{release}
Requires: brasero-license = %{version}-%{release}

%description bin
bin components for the brasero package.


%package data
Summary: data components for the brasero package.
Group: Data

%description data
data components for the brasero package.


%package dev
Summary: dev components for the brasero package.
Group: Development
Requires: brasero-lib = %{version}-%{release}
Requires: brasero-bin = %{version}-%{release}
Requires: brasero-data = %{version}-%{release}
Provides: brasero-devel = %{version}-%{release}
Requires: brasero = %{version}-%{release}

%description dev
dev components for the brasero package.


%package doc
Summary: doc components for the brasero package.
Group: Documentation
Requires: brasero-man = %{version}-%{release}

%description doc
doc components for the brasero package.


%package lib
Summary: lib components for the brasero package.
Group: Libraries
Requires: brasero-data = %{version}-%{release}
Requires: brasero-license = %{version}-%{release}

%description lib
lib components for the brasero package.


%package license
Summary: license components for the brasero package.
Group: Default

%description license
license components for the brasero package.


%package locales
Summary: locales components for the brasero package.
Group: Default

%description locales
locales components for the brasero package.


%package man
Summary: man components for the brasero package.
Group: Default

%description man
man components for the brasero package.


%prep
%setup -q -n brasero-3.12.2
cd %{_builddir}/brasero-3.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586222319
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1586222319
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/brasero
cp %{_builddir}/brasero-3.12.2/COPYING %{buildroot}/usr/share/package-licenses/brasero/a8fbfe9ec1bf1ce3c2bcb36856039d122f229df1
cp %{_builddir}/brasero-3.12.2/libbrasero-media/COPYING %{buildroot}/usr/share/package-licenses/brasero/785d1499112c04b7b6261d1f0cf626211327e835
%make_install
%find_lang brasero

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/brasero

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/BraseroBurn-3.1.typelib
/usr/lib64/girepository-1.0/BraseroMedia-3.1.typelib
/usr/share/GConf/gsettings/brasero.convert
/usr/share/appdata/brasero.appdata.xml
/usr/share/applications/brasero-nautilus.desktop
/usr/share/applications/brasero.desktop
/usr/share/brasero/icons/hicolor/16x16/actions/insert-pause.png
/usr/share/brasero/icons/hicolor/16x16/actions/iso-image-burn.png
/usr/share/brasero/icons/hicolor/16x16/actions/iso-image-new.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-audio-new.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-blank.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-burn.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-copy.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-data-new.png
/usr/share/brasero/icons/hicolor/16x16/actions/media-optical-video-new.png
/usr/share/brasero/icons/hicolor/16x16/actions/transform-crop-and-resize.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-00.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-05.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-10.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-100.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-15.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-20.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-25.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-30.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-35.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-40.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-45.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-50.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-55.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-60.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-65.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-70.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-75.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-80.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-85.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-90.png
/usr/share/brasero/icons/hicolor/16x16/status/brasero-disc-95.png
/usr/share/brasero/icons/hicolor/22x22/actions/insert-pause.png
/usr/share/brasero/icons/hicolor/22x22/actions/iso-image-burn.png
/usr/share/brasero/icons/hicolor/22x22/actions/iso-image-new.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-audio-new.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-blank.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-burn.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-copy.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-data-new.png
/usr/share/brasero/icons/hicolor/22x22/actions/media-optical-video-new.png
/usr/share/brasero/icons/hicolor/22x22/actions/transform-crop-and-resize.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-00.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-05.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-10.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-100.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-15.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-20.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-25.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-30.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-35.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-40.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-45.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-50.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-55.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-60.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-65.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-70.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-75.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-80.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-85.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-90.png
/usr/share/brasero/icons/hicolor/22x22/status/brasero-disc-95.png
/usr/share/brasero/icons/hicolor/24x24/actions/insert-pause.png
/usr/share/brasero/icons/hicolor/24x24/actions/iso-image-burn.png
/usr/share/brasero/icons/hicolor/24x24/actions/iso-image-new.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-audio-new.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-blank.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-burn.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-copy.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-data-new.png
/usr/share/brasero/icons/hicolor/24x24/actions/media-optical-video-new.png
/usr/share/brasero/icons/hicolor/24x24/actions/transform-crop-and-resize.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-00.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-05.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-10.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-100.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-15.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-20.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-25.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-30.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-35.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-40.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-45.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-50.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-55.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-60.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-65.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-70.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-75.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-80.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-85.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-90.png
/usr/share/brasero/icons/hicolor/24x24/status/brasero-disc-95.png
/usr/share/brasero/icons/hicolor/32x32/actions/insert-pause.png
/usr/share/brasero/icons/hicolor/32x32/actions/iso-image-burn.png
/usr/share/brasero/icons/hicolor/32x32/actions/iso-image-new.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-audio-new.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-blank.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-burn.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-copy.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-data-new.png
/usr/share/brasero/icons/hicolor/32x32/actions/media-optical-video-new.png
/usr/share/brasero/icons/hicolor/32x32/actions/transform-crop-and-resize.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-00.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-05.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-10.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-100.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-15.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-20.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-25.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-30.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-35.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-40.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-45.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-50.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-55.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-60.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-65.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-70.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-75.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-80.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-85.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-90.png
/usr/share/brasero/icons/hicolor/32x32/status/brasero-disc-95.png
/usr/share/brasero/icons/hicolor/48x48/actions/media-optical-video-new.png
/usr/share/brasero/icons/hicolor/scalable/actions/insert-pause.svg
/usr/share/brasero/icons/hicolor/scalable/actions/iso-image-burn.svg
/usr/share/brasero/icons/hicolor/scalable/actions/iso-image-new.svg
/usr/share/brasero/icons/hicolor/scalable/actions/media-optical-audio-new.svg
/usr/share/brasero/icons/hicolor/scalable/actions/media-optical-blank.svg
/usr/share/brasero/icons/hicolor/scalable/actions/media-optical-burn.svg
/usr/share/brasero/icons/hicolor/scalable/actions/media-optical-copy.svg
/usr/share/brasero/icons/hicolor/scalable/actions/media-optical-data-new.svg
/usr/share/brasero/icons/hicolor/scalable/actions/transform-crop-and-resize.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-00.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-05.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-10.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-100.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-15.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-20.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-25.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-30.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-35.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-40.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-45.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-50.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-55.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-60.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-65.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-70.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-75.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-80.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-85.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-90.svg
/usr/share/brasero/icons/hicolor/scalable/status/brasero-disc-95.svg
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.brasero.gschema.xml
/usr/share/icons/hicolor/16x16/apps/brasero.png
/usr/share/icons/hicolor/22x22/apps/brasero.png
/usr/share/icons/hicolor/24x24/apps/brasero.png
/usr/share/icons/hicolor/256x256/apps/brasero.png
/usr/share/icons/hicolor/32x32/apps/brasero.png
/usr/share/icons/hicolor/48x48/apps/brasero.png
/usr/share/icons/hicolor/scalable/apps/brasero-symbolic.svg
/usr/share/mime-packages/brasero.xml

%files dev
%defattr(-,root,root,-)
/usr/include/brasero3/brasero-blank-dialog.h
/usr/include/brasero3/brasero-burn-dialog.h
/usr/include/brasero3/brasero-burn-lib.h
/usr/include/brasero3/brasero-burn-options.h
/usr/include/brasero3/brasero-burn.h
/usr/include/brasero3/brasero-drive-selection.h
/usr/include/brasero3/brasero-drive.h
/usr/include/brasero3/brasero-enums.h
/usr/include/brasero3/brasero-error.h
/usr/include/brasero3/brasero-media.h
/usr/include/brasero3/brasero-medium-monitor.h
/usr/include/brasero3/brasero-medium-selection.h
/usr/include/brasero3/brasero-medium.h
/usr/include/brasero3/brasero-session-cfg.h
/usr/include/brasero3/brasero-session-span.h
/usr/include/brasero3/brasero-session.h
/usr/include/brasero3/brasero-status.h
/usr/include/brasero3/brasero-sum-dialog.h
/usr/include/brasero3/brasero-tags.h
/usr/include/brasero3/brasero-tool-dialog.h
/usr/include/brasero3/brasero-track-data-cfg.h
/usr/include/brasero3/brasero-track-data.h
/usr/include/brasero3/brasero-track-disc.h
/usr/include/brasero3/brasero-track-image-cfg.h
/usr/include/brasero3/brasero-track-image.h
/usr/include/brasero3/brasero-track-stream-cfg.h
/usr/include/brasero3/brasero-track-stream.h
/usr/include/brasero3/brasero-track-type.h
/usr/include/brasero3/brasero-track.h
/usr/include/brasero3/brasero-units.h
/usr/include/brasero3/brasero-volume.h
/usr/lib64/libbrasero-burn3.so
/usr/lib64/libbrasero-media3.so
/usr/lib64/libbrasero-utils3.so
/usr/lib64/pkgconfig/libbrasero-burn3.pc
/usr/lib64/pkgconfig/libbrasero-media3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libbrasero-burn/annotation-glossary.html
/usr/share/gtk-doc/html/libbrasero-burn/api-index-full.html
/usr/share/gtk-doc/html/libbrasero-burn/ch01.html
/usr/share/gtk-doc/html/libbrasero-burn/home.png
/usr/share/gtk-doc/html/libbrasero-burn/index.html
/usr/share/gtk-doc/html/libbrasero-burn/left-insensitive.png
/usr/share/gtk-doc/html/libbrasero-burn/left.png
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroBlankDialog.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroBurn.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroBurnDialog.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroBurnOptions.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroBurnSession.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroSessionCfg.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroSessionSpan.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroSumDialog.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroToolDialog.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrack.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrackDisc.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrackImage.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrackImageCfg.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrackStream.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-BraseroTrackStreamCfg.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-burn-lib.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-enums.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-error.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-status.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-tags.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-track-data-cfg.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-track-data.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn-brasero-track-type.html
/usr/share/gtk-doc/html/libbrasero-burn/libbrasero-burn.devhelp2
/usr/share/gtk-doc/html/libbrasero-burn/object-tree.html
/usr/share/gtk-doc/html/libbrasero-burn/right-insensitive.png
/usr/share/gtk-doc/html/libbrasero-burn/right.png
/usr/share/gtk-doc/html/libbrasero-burn/style.css
/usr/share/gtk-doc/html/libbrasero-burn/up-insensitive.png
/usr/share/gtk-doc/html/libbrasero-burn/up.png
/usr/share/gtk-doc/html/libbrasero-media/annotation-glossary.html
/usr/share/gtk-doc/html/libbrasero-media/api-index-full.html
/usr/share/gtk-doc/html/libbrasero-media/ch01.html
/usr/share/gtk-doc/html/libbrasero-media/home.png
/usr/share/gtk-doc/html/libbrasero-media/index.html
/usr/share/gtk-doc/html/libbrasero-media/left-insensitive.png
/usr/share/gtk-doc/html/libbrasero-media/left.png
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-BraseroDriveSelection.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-BraseroMedium.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-BraseroMediumMonitor.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-BraseroMediumSelection.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-BraseroVolume.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-brasero-drive.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-brasero-media.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media-brasero-units.html
/usr/share/gtk-doc/html/libbrasero-media/libbrasero-media.devhelp2
/usr/share/gtk-doc/html/libbrasero-media/object-tree.html
/usr/share/gtk-doc/html/libbrasero-media/right-insensitive.png
/usr/share/gtk-doc/html/libbrasero-media/right.png
/usr/share/gtk-doc/html/libbrasero-media/style.css
/usr/share/gtk-doc/html/libbrasero-media/up-insensitive.png
/usr/share/gtk-doc/html/libbrasero-media/up.png
/usr/share/help/C/brasero/create-cover.page
/usr/share/help/C/brasero/figures/brasero-main-window.png
/usr/share/help/C/brasero/figures/logo48.png
/usr/share/help/C/brasero/index.page
/usr/share/help/C/brasero/introduction.page
/usr/share/help/C/brasero/prob-cd.page
/usr/share/help/C/brasero/prob-dvd.page
/usr/share/help/C/brasero/project-audio.page
/usr/share/help/C/brasero/project-data.page
/usr/share/help/C/brasero/project-disc-copy.page
/usr/share/help/C/brasero/project-image-burn.page
/usr/share/help/C/brasero/project-save.page
/usr/share/help/C/brasero/project-video.page
/usr/share/help/C/brasero/split-track.page
/usr/share/help/C/brasero/tools-blank.page
/usr/share/help/C/brasero/tools-check-integrity.page
/usr/share/help/bg/brasero/create-cover.page
/usr/share/help/bg/brasero/figures/brasero-main-window.png
/usr/share/help/bg/brasero/figures/logo48.png
/usr/share/help/bg/brasero/index.page
/usr/share/help/bg/brasero/introduction.page
/usr/share/help/bg/brasero/prob-cd.page
/usr/share/help/bg/brasero/prob-dvd.page
/usr/share/help/bg/brasero/project-audio.page
/usr/share/help/bg/brasero/project-data.page
/usr/share/help/bg/brasero/project-disc-copy.page
/usr/share/help/bg/brasero/project-image-burn.page
/usr/share/help/bg/brasero/project-save.page
/usr/share/help/bg/brasero/project-video.page
/usr/share/help/bg/brasero/split-track.page
/usr/share/help/bg/brasero/tools-blank.page
/usr/share/help/bg/brasero/tools-check-integrity.page
/usr/share/help/ca/brasero/create-cover.page
/usr/share/help/ca/brasero/figures/brasero-main-window.png
/usr/share/help/ca/brasero/figures/logo48.png
/usr/share/help/ca/brasero/index.page
/usr/share/help/ca/brasero/introduction.page
/usr/share/help/ca/brasero/prob-cd.page
/usr/share/help/ca/brasero/prob-dvd.page
/usr/share/help/ca/brasero/project-audio.page
/usr/share/help/ca/brasero/project-data.page
/usr/share/help/ca/brasero/project-disc-copy.page
/usr/share/help/ca/brasero/project-image-burn.page
/usr/share/help/ca/brasero/project-save.page
/usr/share/help/ca/brasero/project-video.page
/usr/share/help/ca/brasero/split-track.page
/usr/share/help/ca/brasero/tools-blank.page
/usr/share/help/ca/brasero/tools-check-integrity.page
/usr/share/help/cs/brasero/create-cover.page
/usr/share/help/cs/brasero/figures/brasero-main-window.png
/usr/share/help/cs/brasero/figures/logo48.png
/usr/share/help/cs/brasero/index.page
/usr/share/help/cs/brasero/introduction.page
/usr/share/help/cs/brasero/prob-cd.page
/usr/share/help/cs/brasero/prob-dvd.page
/usr/share/help/cs/brasero/project-audio.page
/usr/share/help/cs/brasero/project-data.page
/usr/share/help/cs/brasero/project-disc-copy.page
/usr/share/help/cs/brasero/project-image-burn.page
/usr/share/help/cs/brasero/project-save.page
/usr/share/help/cs/brasero/project-video.page
/usr/share/help/cs/brasero/split-track.page
/usr/share/help/cs/brasero/tools-blank.page
/usr/share/help/cs/brasero/tools-check-integrity.page
/usr/share/help/de/brasero/create-cover.page
/usr/share/help/de/brasero/figures/brasero-main-window.png
/usr/share/help/de/brasero/figures/logo48.png
/usr/share/help/de/brasero/index.page
/usr/share/help/de/brasero/introduction.page
/usr/share/help/de/brasero/prob-cd.page
/usr/share/help/de/brasero/prob-dvd.page
/usr/share/help/de/brasero/project-audio.page
/usr/share/help/de/brasero/project-data.page
/usr/share/help/de/brasero/project-disc-copy.page
/usr/share/help/de/brasero/project-image-burn.page
/usr/share/help/de/brasero/project-save.page
/usr/share/help/de/brasero/project-video.page
/usr/share/help/de/brasero/split-track.page
/usr/share/help/de/brasero/tools-blank.page
/usr/share/help/de/brasero/tools-check-integrity.page
/usr/share/help/el/brasero/create-cover.page
/usr/share/help/el/brasero/figures/brasero-main-window.png
/usr/share/help/el/brasero/figures/logo48.png
/usr/share/help/el/brasero/index.page
/usr/share/help/el/brasero/introduction.page
/usr/share/help/el/brasero/prob-cd.page
/usr/share/help/el/brasero/prob-dvd.page
/usr/share/help/el/brasero/project-audio.page
/usr/share/help/el/brasero/project-data.page
/usr/share/help/el/brasero/project-disc-copy.page
/usr/share/help/el/brasero/project-image-burn.page
/usr/share/help/el/brasero/project-save.page
/usr/share/help/el/brasero/project-video.page
/usr/share/help/el/brasero/split-track.page
/usr/share/help/el/brasero/tools-blank.page
/usr/share/help/el/brasero/tools-check-integrity.page
/usr/share/help/en_GB/brasero/create-cover.page
/usr/share/help/en_GB/brasero/figures/brasero-main-window.png
/usr/share/help/en_GB/brasero/figures/logo48.png
/usr/share/help/en_GB/brasero/index.page
/usr/share/help/en_GB/brasero/introduction.page
/usr/share/help/en_GB/brasero/prob-cd.page
/usr/share/help/en_GB/brasero/prob-dvd.page
/usr/share/help/en_GB/brasero/project-audio.page
/usr/share/help/en_GB/brasero/project-data.page
/usr/share/help/en_GB/brasero/project-disc-copy.page
/usr/share/help/en_GB/brasero/project-image-burn.page
/usr/share/help/en_GB/brasero/project-save.page
/usr/share/help/en_GB/brasero/project-video.page
/usr/share/help/en_GB/brasero/split-track.page
/usr/share/help/en_GB/brasero/tools-blank.page
/usr/share/help/en_GB/brasero/tools-check-integrity.page
/usr/share/help/es/brasero/create-cover.page
/usr/share/help/es/brasero/figures/brasero-main-window.png
/usr/share/help/es/brasero/figures/logo48.png
/usr/share/help/es/brasero/index.page
/usr/share/help/es/brasero/introduction.page
/usr/share/help/es/brasero/prob-cd.page
/usr/share/help/es/brasero/prob-dvd.page
/usr/share/help/es/brasero/project-audio.page
/usr/share/help/es/brasero/project-data.page
/usr/share/help/es/brasero/project-disc-copy.page
/usr/share/help/es/brasero/project-image-burn.page
/usr/share/help/es/brasero/project-save.page
/usr/share/help/es/brasero/project-video.page
/usr/share/help/es/brasero/split-track.page
/usr/share/help/es/brasero/tools-blank.page
/usr/share/help/es/brasero/tools-check-integrity.page
/usr/share/help/eu/brasero/create-cover.page
/usr/share/help/eu/brasero/figures/brasero-main-window.png
/usr/share/help/eu/brasero/figures/logo48.png
/usr/share/help/eu/brasero/index.page
/usr/share/help/eu/brasero/introduction.page
/usr/share/help/eu/brasero/prob-cd.page
/usr/share/help/eu/brasero/prob-dvd.page
/usr/share/help/eu/brasero/project-audio.page
/usr/share/help/eu/brasero/project-data.page
/usr/share/help/eu/brasero/project-disc-copy.page
/usr/share/help/eu/brasero/project-image-burn.page
/usr/share/help/eu/brasero/project-save.page
/usr/share/help/eu/brasero/project-video.page
/usr/share/help/eu/brasero/split-track.page
/usr/share/help/eu/brasero/tools-blank.page
/usr/share/help/eu/brasero/tools-check-integrity.page
/usr/share/help/fi/brasero/create-cover.page
/usr/share/help/fi/brasero/figures/brasero-main-window.png
/usr/share/help/fi/brasero/figures/logo48.png
/usr/share/help/fi/brasero/index.page
/usr/share/help/fi/brasero/introduction.page
/usr/share/help/fi/brasero/prob-cd.page
/usr/share/help/fi/brasero/prob-dvd.page
/usr/share/help/fi/brasero/project-audio.page
/usr/share/help/fi/brasero/project-data.page
/usr/share/help/fi/brasero/project-disc-copy.page
/usr/share/help/fi/brasero/project-image-burn.page
/usr/share/help/fi/brasero/project-save.page
/usr/share/help/fi/brasero/project-video.page
/usr/share/help/fi/brasero/split-track.page
/usr/share/help/fi/brasero/tools-blank.page
/usr/share/help/fi/brasero/tools-check-integrity.page
/usr/share/help/fr/brasero/create-cover.page
/usr/share/help/fr/brasero/figures/brasero-main-window.png
/usr/share/help/fr/brasero/figures/logo48.png
/usr/share/help/fr/brasero/index.page
/usr/share/help/fr/brasero/introduction.page
/usr/share/help/fr/brasero/prob-cd.page
/usr/share/help/fr/brasero/prob-dvd.page
/usr/share/help/fr/brasero/project-audio.page
/usr/share/help/fr/brasero/project-data.page
/usr/share/help/fr/brasero/project-disc-copy.page
/usr/share/help/fr/brasero/project-image-burn.page
/usr/share/help/fr/brasero/project-save.page
/usr/share/help/fr/brasero/project-video.page
/usr/share/help/fr/brasero/split-track.page
/usr/share/help/fr/brasero/tools-blank.page
/usr/share/help/fr/brasero/tools-check-integrity.page
/usr/share/help/gl/brasero/create-cover.page
/usr/share/help/gl/brasero/figures/brasero-main-window.png
/usr/share/help/gl/brasero/figures/logo48.png
/usr/share/help/gl/brasero/index.page
/usr/share/help/gl/brasero/introduction.page
/usr/share/help/gl/brasero/prob-cd.page
/usr/share/help/gl/brasero/prob-dvd.page
/usr/share/help/gl/brasero/project-audio.page
/usr/share/help/gl/brasero/project-data.page
/usr/share/help/gl/brasero/project-disc-copy.page
/usr/share/help/gl/brasero/project-image-burn.page
/usr/share/help/gl/brasero/project-save.page
/usr/share/help/gl/brasero/project-video.page
/usr/share/help/gl/brasero/split-track.page
/usr/share/help/gl/brasero/tools-blank.page
/usr/share/help/gl/brasero/tools-check-integrity.page
/usr/share/help/hu/brasero/create-cover.page
/usr/share/help/hu/brasero/figures/brasero-main-window.png
/usr/share/help/hu/brasero/figures/logo48.png
/usr/share/help/hu/brasero/index.page
/usr/share/help/hu/brasero/introduction.page
/usr/share/help/hu/brasero/prob-cd.page
/usr/share/help/hu/brasero/prob-dvd.page
/usr/share/help/hu/brasero/project-audio.page
/usr/share/help/hu/brasero/project-data.page
/usr/share/help/hu/brasero/project-disc-copy.page
/usr/share/help/hu/brasero/project-image-burn.page
/usr/share/help/hu/brasero/project-save.page
/usr/share/help/hu/brasero/project-video.page
/usr/share/help/hu/brasero/split-track.page
/usr/share/help/hu/brasero/tools-blank.page
/usr/share/help/hu/brasero/tools-check-integrity.page
/usr/share/help/id/brasero/create-cover.page
/usr/share/help/id/brasero/figures/brasero-main-window.png
/usr/share/help/id/brasero/figures/logo48.png
/usr/share/help/id/brasero/index.page
/usr/share/help/id/brasero/introduction.page
/usr/share/help/id/brasero/prob-cd.page
/usr/share/help/id/brasero/prob-dvd.page
/usr/share/help/id/brasero/project-audio.page
/usr/share/help/id/brasero/project-data.page
/usr/share/help/id/brasero/project-disc-copy.page
/usr/share/help/id/brasero/project-image-burn.page
/usr/share/help/id/brasero/project-save.page
/usr/share/help/id/brasero/project-video.page
/usr/share/help/id/brasero/split-track.page
/usr/share/help/id/brasero/tools-blank.page
/usr/share/help/id/brasero/tools-check-integrity.page
/usr/share/help/it/brasero/create-cover.page
/usr/share/help/it/brasero/figures/brasero-main-window.png
/usr/share/help/it/brasero/figures/logo48.png
/usr/share/help/it/brasero/index.page
/usr/share/help/it/brasero/introduction.page
/usr/share/help/it/brasero/prob-cd.page
/usr/share/help/it/brasero/prob-dvd.page
/usr/share/help/it/brasero/project-audio.page
/usr/share/help/it/brasero/project-data.page
/usr/share/help/it/brasero/project-disc-copy.page
/usr/share/help/it/brasero/project-image-burn.page
/usr/share/help/it/brasero/project-save.page
/usr/share/help/it/brasero/project-video.page
/usr/share/help/it/brasero/split-track.page
/usr/share/help/it/brasero/tools-blank.page
/usr/share/help/it/brasero/tools-check-integrity.page
/usr/share/help/ja/brasero/create-cover.page
/usr/share/help/ja/brasero/figures/brasero-main-window.png
/usr/share/help/ja/brasero/figures/logo48.png
/usr/share/help/ja/brasero/index.page
/usr/share/help/ja/brasero/introduction.page
/usr/share/help/ja/brasero/prob-cd.page
/usr/share/help/ja/brasero/prob-dvd.page
/usr/share/help/ja/brasero/project-audio.page
/usr/share/help/ja/brasero/project-data.page
/usr/share/help/ja/brasero/project-disc-copy.page
/usr/share/help/ja/brasero/project-image-burn.page
/usr/share/help/ja/brasero/project-save.page
/usr/share/help/ja/brasero/project-video.page
/usr/share/help/ja/brasero/split-track.page
/usr/share/help/ja/brasero/tools-blank.page
/usr/share/help/ja/brasero/tools-check-integrity.page
/usr/share/help/ko/brasero/create-cover.page
/usr/share/help/ko/brasero/figures/brasero-main-window.png
/usr/share/help/ko/brasero/figures/logo48.png
/usr/share/help/ko/brasero/index.page
/usr/share/help/ko/brasero/introduction.page
/usr/share/help/ko/brasero/prob-cd.page
/usr/share/help/ko/brasero/prob-dvd.page
/usr/share/help/ko/brasero/project-audio.page
/usr/share/help/ko/brasero/project-data.page
/usr/share/help/ko/brasero/project-disc-copy.page
/usr/share/help/ko/brasero/project-image-burn.page
/usr/share/help/ko/brasero/project-save.page
/usr/share/help/ko/brasero/project-video.page
/usr/share/help/ko/brasero/split-track.page
/usr/share/help/ko/brasero/tools-blank.page
/usr/share/help/ko/brasero/tools-check-integrity.page
/usr/share/help/lv/brasero/create-cover.page
/usr/share/help/lv/brasero/figures/brasero-main-window.png
/usr/share/help/lv/brasero/figures/logo48.png
/usr/share/help/lv/brasero/index.page
/usr/share/help/lv/brasero/introduction.page
/usr/share/help/lv/brasero/prob-cd.page
/usr/share/help/lv/brasero/prob-dvd.page
/usr/share/help/lv/brasero/project-audio.page
/usr/share/help/lv/brasero/project-data.page
/usr/share/help/lv/brasero/project-disc-copy.page
/usr/share/help/lv/brasero/project-image-burn.page
/usr/share/help/lv/brasero/project-save.page
/usr/share/help/lv/brasero/project-video.page
/usr/share/help/lv/brasero/split-track.page
/usr/share/help/lv/brasero/tools-blank.page
/usr/share/help/lv/brasero/tools-check-integrity.page
/usr/share/help/pl/brasero/create-cover.page
/usr/share/help/pl/brasero/figures/brasero-main-window.png
/usr/share/help/pl/brasero/figures/logo48.png
/usr/share/help/pl/brasero/index.page
/usr/share/help/pl/brasero/introduction.page
/usr/share/help/pl/brasero/prob-cd.page
/usr/share/help/pl/brasero/prob-dvd.page
/usr/share/help/pl/brasero/project-audio.page
/usr/share/help/pl/brasero/project-data.page
/usr/share/help/pl/brasero/project-disc-copy.page
/usr/share/help/pl/brasero/project-image-burn.page
/usr/share/help/pl/brasero/project-save.page
/usr/share/help/pl/brasero/project-video.page
/usr/share/help/pl/brasero/split-track.page
/usr/share/help/pl/brasero/tools-blank.page
/usr/share/help/pl/brasero/tools-check-integrity.page
/usr/share/help/pt/brasero/create-cover.page
/usr/share/help/pt/brasero/figures/brasero-main-window.png
/usr/share/help/pt/brasero/figures/logo48.png
/usr/share/help/pt/brasero/index.page
/usr/share/help/pt/brasero/introduction.page
/usr/share/help/pt/brasero/prob-cd.page
/usr/share/help/pt/brasero/prob-dvd.page
/usr/share/help/pt/brasero/project-audio.page
/usr/share/help/pt/brasero/project-data.page
/usr/share/help/pt/brasero/project-disc-copy.page
/usr/share/help/pt/brasero/project-image-burn.page
/usr/share/help/pt/brasero/project-save.page
/usr/share/help/pt/brasero/project-video.page
/usr/share/help/pt/brasero/split-track.page
/usr/share/help/pt/brasero/tools-blank.page
/usr/share/help/pt/brasero/tools-check-integrity.page
/usr/share/help/pt_BR/brasero/create-cover.page
/usr/share/help/pt_BR/brasero/figures/brasero-main-window.png
/usr/share/help/pt_BR/brasero/figures/logo48.png
/usr/share/help/pt_BR/brasero/index.page
/usr/share/help/pt_BR/brasero/introduction.page
/usr/share/help/pt_BR/brasero/prob-cd.page
/usr/share/help/pt_BR/brasero/prob-dvd.page
/usr/share/help/pt_BR/brasero/project-audio.page
/usr/share/help/pt_BR/brasero/project-data.page
/usr/share/help/pt_BR/brasero/project-disc-copy.page
/usr/share/help/pt_BR/brasero/project-image-burn.page
/usr/share/help/pt_BR/brasero/project-save.page
/usr/share/help/pt_BR/brasero/project-video.page
/usr/share/help/pt_BR/brasero/split-track.page
/usr/share/help/pt_BR/brasero/tools-blank.page
/usr/share/help/pt_BR/brasero/tools-check-integrity.page
/usr/share/help/ro/brasero/create-cover.page
/usr/share/help/ro/brasero/figures/brasero-main-window.png
/usr/share/help/ro/brasero/figures/logo48.png
/usr/share/help/ro/brasero/index.page
/usr/share/help/ro/brasero/introduction.page
/usr/share/help/ro/brasero/prob-cd.page
/usr/share/help/ro/brasero/prob-dvd.page
/usr/share/help/ro/brasero/project-audio.page
/usr/share/help/ro/brasero/project-data.page
/usr/share/help/ro/brasero/project-disc-copy.page
/usr/share/help/ro/brasero/project-image-burn.page
/usr/share/help/ro/brasero/project-save.page
/usr/share/help/ro/brasero/project-video.page
/usr/share/help/ro/brasero/split-track.page
/usr/share/help/ro/brasero/tools-blank.page
/usr/share/help/ro/brasero/tools-check-integrity.page
/usr/share/help/ru/brasero/create-cover.page
/usr/share/help/ru/brasero/figures/brasero-main-window.png
/usr/share/help/ru/brasero/figures/logo48.png
/usr/share/help/ru/brasero/index.page
/usr/share/help/ru/brasero/introduction.page
/usr/share/help/ru/brasero/prob-cd.page
/usr/share/help/ru/brasero/prob-dvd.page
/usr/share/help/ru/brasero/project-audio.page
/usr/share/help/ru/brasero/project-data.page
/usr/share/help/ru/brasero/project-disc-copy.page
/usr/share/help/ru/brasero/project-image-burn.page
/usr/share/help/ru/brasero/project-save.page
/usr/share/help/ru/brasero/project-video.page
/usr/share/help/ru/brasero/split-track.page
/usr/share/help/ru/brasero/tools-blank.page
/usr/share/help/ru/brasero/tools-check-integrity.page
/usr/share/help/sl/brasero/create-cover.page
/usr/share/help/sl/brasero/figures/brasero-main-window.png
/usr/share/help/sl/brasero/figures/logo48.png
/usr/share/help/sl/brasero/index.page
/usr/share/help/sl/brasero/introduction.page
/usr/share/help/sl/brasero/prob-cd.page
/usr/share/help/sl/brasero/prob-dvd.page
/usr/share/help/sl/brasero/project-audio.page
/usr/share/help/sl/brasero/project-data.page
/usr/share/help/sl/brasero/project-disc-copy.page
/usr/share/help/sl/brasero/project-image-burn.page
/usr/share/help/sl/brasero/project-save.page
/usr/share/help/sl/brasero/project-video.page
/usr/share/help/sl/brasero/split-track.page
/usr/share/help/sl/brasero/tools-blank.page
/usr/share/help/sl/brasero/tools-check-integrity.page
/usr/share/help/sv/brasero/create-cover.page
/usr/share/help/sv/brasero/figures/brasero-main-window.png
/usr/share/help/sv/brasero/figures/logo48.png
/usr/share/help/sv/brasero/index.page
/usr/share/help/sv/brasero/introduction.page
/usr/share/help/sv/brasero/prob-cd.page
/usr/share/help/sv/brasero/prob-dvd.page
/usr/share/help/sv/brasero/project-audio.page
/usr/share/help/sv/brasero/project-data.page
/usr/share/help/sv/brasero/project-disc-copy.page
/usr/share/help/sv/brasero/project-image-burn.page
/usr/share/help/sv/brasero/project-save.page
/usr/share/help/sv/brasero/project-video.page
/usr/share/help/sv/brasero/split-track.page
/usr/share/help/sv/brasero/tools-blank.page
/usr/share/help/sv/brasero/tools-check-integrity.page
/usr/share/help/te/brasero/create-cover.page
/usr/share/help/te/brasero/figures/brasero-main-window.png
/usr/share/help/te/brasero/figures/logo48.png
/usr/share/help/te/brasero/index.page
/usr/share/help/te/brasero/introduction.page
/usr/share/help/te/brasero/prob-cd.page
/usr/share/help/te/brasero/prob-dvd.page
/usr/share/help/te/brasero/project-audio.page
/usr/share/help/te/brasero/project-data.page
/usr/share/help/te/brasero/project-disc-copy.page
/usr/share/help/te/brasero/project-image-burn.page
/usr/share/help/te/brasero/project-save.page
/usr/share/help/te/brasero/project-video.page
/usr/share/help/te/brasero/split-track.page
/usr/share/help/te/brasero/tools-blank.page
/usr/share/help/te/brasero/tools-check-integrity.page
/usr/share/help/zh_CN/brasero/create-cover.page
/usr/share/help/zh_CN/brasero/figures/brasero-main-window.png
/usr/share/help/zh_CN/brasero/figures/logo48.png
/usr/share/help/zh_CN/brasero/index.page
/usr/share/help/zh_CN/brasero/introduction.page
/usr/share/help/zh_CN/brasero/prob-cd.page
/usr/share/help/zh_CN/brasero/prob-dvd.page
/usr/share/help/zh_CN/brasero/project-audio.page
/usr/share/help/zh_CN/brasero/project-data.page
/usr/share/help/zh_CN/brasero/project-disc-copy.page
/usr/share/help/zh_CN/brasero/project-image-burn.page
/usr/share/help/zh_CN/brasero/project-save.page
/usr/share/help/zh_CN/brasero/project-video.page
/usr/share/help/zh_CN/brasero/split-track.page
/usr/share/help/zh_CN/brasero/tools-blank.page
/usr/share/help/zh_CN/brasero/tools-check-integrity.page
/usr/share/help/zh_HK/brasero/create-cover.page
/usr/share/help/zh_HK/brasero/figures/brasero-main-window.png
/usr/share/help/zh_HK/brasero/figures/logo48.png
/usr/share/help/zh_HK/brasero/index.page
/usr/share/help/zh_HK/brasero/introduction.page
/usr/share/help/zh_HK/brasero/prob-cd.page
/usr/share/help/zh_HK/brasero/prob-dvd.page
/usr/share/help/zh_HK/brasero/project-audio.page
/usr/share/help/zh_HK/brasero/project-data.page
/usr/share/help/zh_HK/brasero/project-disc-copy.page
/usr/share/help/zh_HK/brasero/project-image-burn.page
/usr/share/help/zh_HK/brasero/project-save.page
/usr/share/help/zh_HK/brasero/project-video.page
/usr/share/help/zh_HK/brasero/split-track.page
/usr/share/help/zh_HK/brasero/tools-blank.page
/usr/share/help/zh_HK/brasero/tools-check-integrity.page
/usr/share/help/zh_TW/brasero/create-cover.page
/usr/share/help/zh_TW/brasero/figures/brasero-main-window.png
/usr/share/help/zh_TW/brasero/figures/logo48.png
/usr/share/help/zh_TW/brasero/index.page
/usr/share/help/zh_TW/brasero/introduction.page
/usr/share/help/zh_TW/brasero/prob-cd.page
/usr/share/help/zh_TW/brasero/prob-dvd.page
/usr/share/help/zh_TW/brasero/project-audio.page
/usr/share/help/zh_TW/brasero/project-data.page
/usr/share/help/zh_TW/brasero/project-disc-copy.page
/usr/share/help/zh_TW/brasero/project-image-burn.page
/usr/share/help/zh_TW/brasero/project-save.page
/usr/share/help/zh_TW/brasero/project-video.page
/usr/share/help/zh_TW/brasero/split-track.page
/usr/share/help/zh_TW/brasero/tools-blank.page
/usr/share/help/zh_TW/brasero/tools-check-integrity.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/brasero3/plugins/libbrasero-audio2cue.so
/usr/lib64/brasero3/plugins/libbrasero-burn-uri.so
/usr/lib64/brasero3/plugins/libbrasero-cdda2wav.so
/usr/lib64/brasero3/plugins/libbrasero-cdrdao.so
/usr/lib64/brasero3/plugins/libbrasero-cdrecord.so
/usr/lib64/brasero3/plugins/libbrasero-checksum-file.so
/usr/lib64/brasero3/plugins/libbrasero-checksum.so
/usr/lib64/brasero3/plugins/libbrasero-dvdauthor.so
/usr/lib64/brasero3/plugins/libbrasero-dvdcss.so
/usr/lib64/brasero3/plugins/libbrasero-dvdrwformat.so
/usr/lib64/brasero3/plugins/libbrasero-genisoimage.so
/usr/lib64/brasero3/plugins/libbrasero-growisofs.so
/usr/lib64/brasero3/plugins/libbrasero-libburn.so
/usr/lib64/brasero3/plugins/libbrasero-libisofs.so
/usr/lib64/brasero3/plugins/libbrasero-local-track.so
/usr/lib64/brasero3/plugins/libbrasero-mkisofs.so
/usr/lib64/brasero3/plugins/libbrasero-normalize.so
/usr/lib64/brasero3/plugins/libbrasero-readcd.so
/usr/lib64/brasero3/plugins/libbrasero-readom.so
/usr/lib64/brasero3/plugins/libbrasero-transcode.so
/usr/lib64/brasero3/plugins/libbrasero-vcdimager.so
/usr/lib64/brasero3/plugins/libbrasero-vob.so
/usr/lib64/brasero3/plugins/libbrasero-wodim.so
/usr/lib64/libbrasero-burn3.so.1
/usr/lib64/libbrasero-burn3.so.1.2.6
/usr/lib64/libbrasero-media3.so.1
/usr/lib64/libbrasero-media3.so.1.2.6
/usr/lib64/libbrasero-utils3.so.1
/usr/lib64/libbrasero-utils3.so.1.2.6
/usr/lib64/nautilus/extensions-3.0/libnautilus-brasero-extension.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/brasero/785d1499112c04b7b6261d1f0cf626211327e835
/usr/share/package-licenses/brasero/a8fbfe9ec1bf1ce3c2bcb36856039d122f229df1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/brasero.1

%files locales -f brasero.lang
%defattr(-,root,root,-)

